### ISSUE TITLE
Missing required files for audiocaption evaluation

### ISSUE THREAD

**Issue by jzq2000** [yangdongchao/Text-to-sound-Synthesis#15]
The required files in [AudiocaptionLoss config](https://github.com/yangdongchao/Text-to-sound-Synthesis/blob/master/Codebook/AudiocaptionLoss/settings/settings.yaml#L37) are missing.  
```
path:
  vocabulary: 'data/pickles/words_list.p'
  encoder: 'pretrained_models/audioset_deit.pth'  # 'pretrained_models/deit.pth'
  word2vec: 'pretrained_models/word2vec/w2v_512.model'
  eval_model: 'pretrained_models/ACTm.pth'
```
